version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "5011:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql/data
    networks:
      - app-network

  webapi:
    build:
      context: ./server/Udemy.Server.Api/
      dockerfile: Dockerfile
    image: udemy_backend
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Udemy;User=sa;Password=${SA_PASSWORD};
    depends_on:
      - sqlserver
    volumes:
      - ../../videos:/app/wwwroot/videos
    networks:
      - app-network

  reactjs:
    build:
      context: ./client/
      dockerfile: Dockerfile
    image: udemy_frontend
    ports:
      - "3000:80"
      - "3001:443"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - webapi
    networks:
      - app-network

volumes:
  sqlserver-data:

networks:
  app-network:
