services:
  sqlserver:
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: 'Developer'
    ports:
      - "5011:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql/data
      - sqlserver-log:/var/opt/mssql/log
      - sqlserver-secrets:/var/opt/mssql/secrets
    networks:
      - app-network
    user: "0:0"

  webapi:
    build:
      context: ./server/Udemy.Server.Api/
      dockerfile: Dockerfile
    image: udemy_backend
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=Udemy;User=sa;Password=${SA_PASSWORD};"
    depends_on:
      - sqlserver
    volumes:
      - ../videos:/app/videos
    networks:
      - app-network

  reactjs:
    build:
      context: ./client/
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    image: udemy_frontend
    ports:
      - "3000:80"
    depends_on:
      - webapi
    networks:
      - app-network
      
volumes:
  sqlserver-data:
  sqlserver-log:
  sqlserver-secrets:

networks:
  app-network:
